version: '3.4'

networks:
  dev:
    driver: bridge

services:
  micro-code:
    image: docker.io/library/microcode
    depends_on:
      - "dataBase"
    container_name: MicroCodeService
    ports:
      - "8080:80"
    build:
      context: ./MicroCode/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=dataBase;Port=5432;Database=postgres;Username=postgres;Password=microcode;Pooling=true;
    command: sh -c "dotnet ef database update --context ApplicationDbContext && dotnet MicroCode.dll"
    networks:
      - dev
  dataBase:
    image: postgres:latest
    container_name: microcode_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=microcode
      - POSTGRES_DB=postgres
    ports:
      - "5439:5432"
    expose:
      - 5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  db_data:
