version: '3.4'

networks:
  dev:
    driver: bridge

services:
  micro-code:
    image: docker.io/library/microcode
    depends_on:
      - "dataBase"
    container_name: MicroCodeService
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=dataBase;Port=5432;Database=testDatabase;Username=postgres;Password=microcode;Pooling=true;
    
    networks:
      - dev
  dataBase:
    image: postgres:latest
    container_name: microcode_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=microcode
      - POSTGRES_DB=testDatabase
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  db_data:
