GET http://localhost:8080/WeatherForecast HTTP/1.1
Content-Type: application/json
Cookie: Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZGRkZiIsImVtYWlsIjoiZmRhZGFAZW1haWwuY29tIiwic2lkIjoiMjFmYjk2OTEtNjBlNi00Mzc2LThhNGEtZTZlZDQxY2M0MjQ1IiwibmJmIjoxNzEwNzk3MDU1LCJleHAiOjE3MTA3OTc2NTUsImlhdCI6MTcxMDc5NzA1NSwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.tKiMf5ViDBzZKwAi7oyPAJwobMCtw4ul16J_wl1XMQfN2XfVqc2UYw0UksxplmibycusISOiIkfPcAes4kXR5A
###
POST  http://localhost:8080/api/auth HTTP/1.1
Content-Type: application/json


{
   "Email" : "fdada@email.com",
   "Password" : "Sooryagayathri2!"
}
###
POST  http://localhost:8080/signup HTTP/1.1
Content-Type: application/json


{
   "first_name" : "G",
   "last_name" : "s",
   "phone_no": "98495",
   "username": "sdddf",
   "email" : "fdada@email.com",
   "password" : "Sooryagayathri2!"
}
###
// validates username and eamil
// Can be use to provide if username exist or not
POST  http://localhost:8080/exist HTTP/1.1
Content-Type: application/json


{
   "what": "username",
   "value" : "Kiran"
}


###


POST  http://localhost:8080/cProblem HTTP/1.1
Content-Type: application/json


{


 "title": "string",
 "discription": "string",
 "mainCode": "string",
 "template": "string",
 "input": "string",
 "output": "string"
}


###
GET https://judge0-ce.p.rapidapi.com/about,
X-RapidAPI-Key: 'f008f458fbmsh6461d2ec9b97427p11018ajsn57aabd191f57',
X-RapidAPI-Host: 'judge0-ce.p.rapidapi.com'




###
GET http://localhost:8080/createProblem
Content-Type: application/json
Cookie: Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZGRkZiIsImVtYWlsIjoiZmRhZGFAZW1haWwuY29tIiwic2lkIjoiMjFmYjk2OTEtNjBlNi00Mzc2LThhNGEtZTZlZDQxY2M0MjQ1IiwibmJmIjoxNzEwODEyNTM2LCJleHAiOjE3MTA4MTMxMzYsImlhdCI6MTcxMDgxMjUzNiwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.AJDg85n1GtPJSaTYsm0uuyG14vxkQ00_kkUYDmRTwud0Q5AtOZUWFv5VsPM1rvzYTUbE_vKE0UOtpLiM6QdDJQ
title: "Two Sum Problem"


###
Get  http://localhost:8080/getSubmission HTTP/1.1
Content-Type: application/json


Token : 169e2bff-084e-458c-96bc-0fb1f03ab4cf






###
Get  http://localhost:8080/pushSubmission HTTP/1.1
Content-Type: application/json
Token : 169e2bff-084e-458c-96bc-0fb1f03ab4cf









