GET http://localhost:8080/WeatherForecast HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJuYmYiOjE3MDczMTk1NTgsImV4cCI6MTcwNzMxOTYxOCwiaWF0IjoxNzA3MzE5NTU4LCJpc3MiOiJJc3N1ZXIiLCJhdWQiOiJBdWRpZW5jZSJ9.UPwJmEnNBLJaCqUEWMOVTil5CmffqHgOzeKvQzK3fMfwJYi3fdaArTBRIPx8Ljds0SLmeMWxltamDElFvGdFpA
###
POST  http://localhost:8080/api/auth HTTP/1.1
Content-Type: application/json

{
    "Email" : "test@email.com",
    "Password" : "a"
}
###

POST  http://localhost:8080/api/signup HTTP/1.1
Content-Type: application/json

{
    "first_name" : "adarsha",
    "last_name" : "khadka",
    "phone_no": "98",
    "username": "kiran",
    "eamil" : "akk@email.com",
    "password" : "ZeroMode"
}
###